on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
name: 'release'
jobs:
  build:
    steps:
      - name: 'Install Go'
        uses: 'actions/setup-go@v1'
        with:
          go-version: '1.13.x'
      - name: 'Setup Environment'
        shell: 'bash'
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
          git config --global core.autocrlf false
      - name: 'Install UPX'
        shell: 'bash'
        run: |
          sudo apt-get install -qy upx
      - name: 'Install GoReleaser'
        run: |
          git clone https://github.com/goreleaser/goreleaser -b v0.123.3
          cd goreleaser
          go install
      - name: 'Checkout code'
        uses: 'actions/checkout@v1'
      - name: 'Release'
        shell: 'bash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser
